### PR TITLE
Add and remove items from list

### PR DESCRIPTION
**Pull request by ragangithub**
- Updated HTML file
- Updated CSS file
-  Updated JS file
- Added adding , deleting, and editing functionality

### CODE REVIEW

**Review by topeogunleye — COMMENTED** [review]
Hi @ragangithub, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request


Thank you for your recent pull request. Unfortunately, I am unable to review your changes at this time. The reason for this is that your pull request title, "Make it functional," is not in line with the current project milestone of "To Do list: add & remove."

While I appreciate your contributions to the project, it's important that pull request titles accurately reflect the changes being made and align with the project goals. In this case, the focus of the current milestone is on adding and removing items from the to-do list, not on making the application functional in a general sense.

I encourage you to revisit your changes and adjust your pull request title to better align with the current project milestone. This will help ensure that your contributions are appropriately focused and contribute to the overall success of the project.

Thank you for your understanding, and I look forward to seeing your future contributions.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by ragangithub** [comment]
- changed pull request title

**Comment by topeogunleye** [comment]
> * changed pull request title

Have you changes your PR Title because I can see that the PR Title is still "Make it functional"

**Comment by TedLivist** [comment]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @ragangithub,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### Kindly implement the changes requested by the previous reviewer. An example PR title could be "Add and Remove functionality"

image

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by emmiiorji — APPROVED** [review]
Hi @ragangithub,

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<div align='center'>

</div>

## Good Highlights✔️

- All hardcoded items have been removed
- Adding, editing and removing of tasks is implemented
- Changes are saved to the local storage

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
